# Generated by Django 3.1.8 on 2022-09-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('company_license', models.FileField(null=True, upload_to='company_license/')),
                ('passport', models.FileField(null=True, upload_to='passport/')),
                ('national_id', models.FileField(null=True, upload_to='national_id/')),
                ('vat_number', models.FileField(null=True, upload_to='vat_number/')),
            ],
        ),
    ]
