# Generated by Django 3.1.8 on 2022-09-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
