# Generated by Django 3.1.8 on 2022-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_agent_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.CharField(default='asd', max_length=255),
        ),
    ]
